name: CI for Krypton common docker base images
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build the common base images used by Krypton services
      run: make -C base-images build

    - name: Publish the common base images
      run: make -C base-images publish

    - name: Cleanup
      if: always()
      run: make -C base-images clean && docker logout
